[package]
name = "fsmgen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fsmgen-cli"
required-features = ["cli"]

[features]
default = []
cli = ["prettyplease", "clap", "anyhow", "syn-miette", "miette"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", optional = true }
clap = { version = "4.4.6", features = ["derive"], optional = true }
derive-quote-to-tokens = "0.1.0"
derive-syn-parse = "0.1.5"
heck = "0.4.1"
itertools = "0.11.0"
miette = { version = "5.10.0", features = [
    "fancy-no-backtrace",
], optional = true }
prettyplease = { version = "0.2.15", optional = true }
proc-macro2 = { version = "1.0.67", default-features = false }
quote = { version = "1.0.33", default-features = false }
syn = { version = "2.0.37", default-features = false, features = [
    "full",
    "parsing",
    "printing",
    "clone-impls",
] }
syn-graphs = { version = "0.1.0", path = "../syn-graphs" }
syn-miette = { version = "0.1.0", optional = true }

[dev-dependencies]
derive-quickcheck-arbitrary = "0.1.3"
pretty_assertions = "1.4.0"
quickcheck = "1.0.3"
syn = { version = "2.0.37", features = ["extra-traits"] }
