[package]
name = "fsmentry"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fsmentry-cli"
required-features = ["cli"]

[features]
default = []
cli = [
    "prettyplease",
    "clap",
    "anyhow",
    "syn-miette",
    "miette",
    "syn",
    "syn-graphs",
    "quote",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", optional = true }
clap = { version = "4.4.6", features = ["derive"], optional = true }
syn-miette = { version = "0.1.0", optional = true }
miette = { version = "5.10.0", features = [
    "fancy-no-backtrace",
], optional = true }
prettyplease = { version = "0.2.15", optional = true }
fsmentry-core.workspace = true
syn = { workspace = true, optional = true }
syn-graphs = { workspace = true, optional = true }
quote = { workspace = true, optional = true }


[dev-dependencies]
derive-quickcheck-arbitrary = "0.1.3"
pretty_assertions = "1.4.0"
quickcheck = "1.0.3"
syn = { workspace = true, features = ["extra-traits"] }

[workspace]
members = ["core", "macros"]

[workspace.dependencies]
syn = { version = "2.0.37", default-features = false }
fsmentry-core = { path = "core" }
fsmentry-macros = { path = "macros" }
syn-graphs = { version = "0.1.0", path = "../syn-graphs" }
quote = { version = "1.0.33", default-features = false }
