[package]
name = "fsmentry-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-quote-to-tokens = "0.1.0"
derive-syn-parse = "0.1.5"
heck = "0.4.1"
itertools = "0.11.0"
proc-macro2 = { version = "1.0.67", default-features = false }
syn = { workspace = true, features = ["full", "parsing", "clone-impls"] }
syn-graphs.workspace = true
quote.workspace = true
